INSERT INTO PRODUCTS("ID","NAME","TYPE","PRODUCT_TYPE","PRICE") VALUES (1,'Cevapi','rostilj','FOOD',15.56);
INSERT INTO PRODUCTS("ID","NAME","TYPE","PRODUCT_TYPE","PRICE") VALUES (2,'Raznjici','rostilj','FOOD',15.04);
INSERT INTO PRODUCTS("ID","NAME","TYPE","PRODUCT_TYPE","PRICE") VALUES (3,'Cola-Cola','gazirano','BEVERAGE',2.56);